#!/bin/sh

echo -n 'User 1 name: '
read name1

echo -n 'User 2 name: '
read name2

gnome-terminal -e "bash -c './client -s 127.0.0.1:5000 -p 1234 -n $name1;exec $SHELL'"
gnome-terminal -e "bash -c './client -s 127.0.0.1:5000 -p 1235 -n $name2;exec $SHELL'"

